[programs.localnet]
nft = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/srinivasvalekar/.config/solana/id.json"

[scripts]
#test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**"
test = "yarn ts-mocha  -p ./tsconfig.json -t 30000 tests/**"